### PR TITLE
AppVeyor with artifact packaging

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
Let's hope this all works...

### CODE REVIEW

**Comment by Narann** [comment]
Tell me if I'm wrong but this seems to prepare full release am I right?

**Comment by Jj0YzL5nvJ** [comment]
That's right, if you prefer only the CLI + the dependencies just say it. Anyone is fine by me.

**Comment by Jj0YzL5nvJ** [comment]
I pushed a normal implementation in the last second =P

**Comment by Narann** [comment]
I prefer this one for now, maybe we could open a repo to download latest artifacts and package a release. Dunno.

**Pull request merged**
