### PR TITLE
Add basic support for 64DD.

### PR DESCRIPTION
**Pull request by bsmiles32**
This goes with PR https://github.com/mupen64plus/mupen64plus-core/pull/446 and add basic 64DD support.

Definition of DD IPL rom and disk is done through the mupen64plus.cfg
file as follow:

[64DD]
IPL-ROM="path/to/64DD_IPL_ROM.bin"
Disk="path/to/64DDDisk.ndd"

Setting an empty IPL-ROM disable the 64DD.
Setting an empty Disk acts as if the 64DD had no disk plugged in.

You can also specify these at program startup using command-line
arguments --dd-ipl-rom and --dd-disk.

### CODE REVIEW

**Comment by loganmc10** [comment]
How does this work without a ROM file?

If I try to just specify the IPL rom and the dd disk, I get "UI-Console Error: no ROM filepath given"

**Comment by bsmiles32** [comment]
This is still WIP as you can see...
You need to pass a path to a cart rom, even if none is strictly required. Don't worry, the IPL boot rom willing select the disk if you have one inserted, or just show the boot menu otherwise

**Comment by bsmiles32** [comment]
rebase against master

**Comment by LuigiBlood** [comment]
Should be merged as well.

**Comment by Narann** [comment]
It has troubles with CI and @bsmiles32 states it's still WIP.

**Comment by LuigiBlood** [comment]
oh okay.

**Comment by bsmiles32** [comment]
This should also be merged I think even if it is only a partial solution (sorry for not updating the WIP tag in the title).

The problem with needing loading a ROM even if no cart ROM is needed for the 64DD is more related to the core because it was coded with that expectation. We can remove this requirement at a later time. For now all we need to remember is to use a Japanese ROM (otherwise some region check will fail) with same features as the 64DD game we want to play (think RumblePak, TransferPak, otherwise, they won't be available).

There is a sibling issue also with 64DD games is that there are no entries in the game db (mupen64plus.ini) for them, and the core currently only relies on the cart ROM loaded to fetch the ROM infos.

**Pull request merged**
