### PR TITLE
Allow non-default compilers without resorting to symbolic links

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
mupen64plus/mupen64plus-core#775

### CODE REVIEW

**Comment by joolswills** [comment]
Sorry but this seems wrong.

CC is already set by gnu make to "cc" so it will not be set at all now to gcc unless set as a make parameter manually.

https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

Usually overriding CC is enough without this, so if that didn't work maybe the fault is elsewhere in the makefile. This isn't the way to fix it imho.

**Comment by joolswills** [comment]
This also has broken building for people. Workaround is to do something like

`make CC=gcc CXX=g++`

But imho this change should be reverted as it's not expected behaviour.

**Comment by richard42** [comment]
okay, I have reverted these changes.
@Jj0YzL5nvJ @joolswills would it work for both of you if we did the following instead?
`CC        = $(CROSS_COMPILE)$(CC)`

**Comment by joolswills** [comment]
That would still set it to `cc` I think. Which wouldn't fix it

**Comment by joolswills** [comment]
Might get a recursive error issue also.

**Comment by Jj0YzL5nvJ** [comment]
What's happens if you replace $(CROSS_COMPILE) with ${CROSS_COMPILE}?

**Comment by joolswills** [comment]
If the purpose is to have a variable for a different gcc path for a cross compiler this isn't the right way imho.

For such a case you should override the entire CC and CXX bars with full binary path. No need to do it by concatenating in the makefile . For cross compiler arguments they can be done via CFLAGS and CXXFLAGS etc.

But maybe I'm not clear on the issue ?

**Comment by Jj0YzL5nvJ** [comment]
The Makefiles are using `$ ()` instead of `$ {}` in parts where it's not safe...

My symbolic link hell:

**$HOME/.local/bin:**
```
cc -> /usr/bin/clang-8
clang -> /usr/bin/clang-8
clang++ -> /usr/bin/clang++-8
g++ -> /usr/bin/clang++-8
gcc -> /usr/bin/clang-8
```
**/usr/bin:**
```
/usr/bin/cc -> /etc/alternatives/cc
/etc/alternatives/cc -> /usr/bin/gcc
/usr/bin/g++ -> g++-5
/usr/bin/g++-5
/usr/bin/g++-6 -> x86_64-linux-gnu-g++-6
/usr/bin/g++-7 -> x86_64-linux-gnu-g++-7
/usr/bin/g++-8 -> x86_64-linux-gnu-g++-8
/usr/bin/g++-9 -> x86_64-linux-gnu-g++-9
/usr/bin/gcc -> gcc-5
/usr/bin/gcc -> gcc-5
/usr/bin/gcc-5
/usr/bin/gcc-6 -> x86_64-linux-gnu-gcc-6
/usr/bin/gcc-7 -> x86_64-linux-gnu-gcc-7
/usr/bin/gcc-8 -> x86_64-linux-gnu-gcc-8
/usr/bin/gcc-9 -> x86_64-linux-gnu-gcc-9
/usr/bin/clang-4.0 -> ../lib/llvm-4.0/bin/clang
/usr/bin/clang++-4.0 -> ../lib/llvm-4.0/bin/clang++
/usr/bin/clang-5.0 -> ../lib/llvm-5.0/bin/clang
/usr/bin/clang++-5.0 -> ../lib/llvm-5.0/bin/clang++
/usr/bin/clang-6.0 -> ../lib/llvm-6.0/bin/clang
/usr/bin/clang++-6.0 -> ../lib/llvm-6.0/bin/clang++
/usr/bin/clang-7 -> ../lib/llvm-7/bin/clang
/usr/bin/clang++-7 -> ../lib/llvm-7/bin/clang++
/usr/bin/clang-8 -> ../lib/llvm-8/bin/clang
/usr/bin/clang++-8 -> ../lib/llvm-8/bin/clang++
```

**Comment by Jj0YzL5nvJ** [comment]
Prior to this comment the Makefile has been overwriting the environment variables... my workaround is doing this:
```
export CC=clang-8
export CXX=clang++-8
mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/cc
rm -f $HOME/.local/bin/gcc
rm -f $HOME/.local/bin/c++
rm -f $HOME/.local/bin/g++
ln -s -T /usr/bin/$CC $HOME/.local/bin/cc
ln -s -T /usr/bin/$CC $HOME/.local/bin/gcc
ln -s -T /usr/bin/$CXX $HOME/.local/bin/c++
ln -s -T /usr/bin/$CXX $HOME/.local/bin/g++
```

I can keep doing this without problem, whatever. You are not the only project with "peculiarities". This rollback only masks the real issues in the environment of the user.
```
#!/bin/bash
echo ""
echo "1=$CC 2=${CC} 3=$(CC)"
echo "4=$CXX 5=${CXX} 6=$(CXX)"
echo "7=$AS 8=${AS} 9=$(AS)"
echo ""

```

<details>
  <summary>Expected result</summary>
  
</details>

**Comment by Jj0YzL5nvJ** [comment]
Well, the rollback is justified and effective. I would just like to clarify a few things and not seem even more idiotic...

The necessary steps to reproduce this error are to create a symbolic link to '`cc`' pointing to a C compiler and create another symbolic link to '`g++`' pointing to a C ++ compiler of a different version than said C compiler.

Example in user space:
```
mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/cc
rm -f $HOME/.local/bin/g++
ln -s -T /usr/bin/gcc-8 $HOME/.local/bin/cc
ln -s -T /usr/bin/g++-9 $HOME/.local/bin/g++
```

Normally '`cc`' points to '`gcc`' and '`gcc`' in turn points to a stable version of said C compiler that normally matches '`c++`' and '`g++`' pointing to the same version of the C++ compiler.

Example:
```
/usr/bin/cc -> /etc/alternatives/cc
/etc/alternatives/cc -> /usr/bin/gcc
/usr/bin/gcc -> gcc-5
/usr/bin/gcc-5
/usr/bin/c++ -> /etc/alternatives/c++
/etc/alternatives/c++ -> /usr/bin/g++
/usr/bin/g++ -> g++-5
/usr/bin/g++-5
```

In theory, the '`?=`' in the Makefile syntax should set `CC` and `CXX` as '`$(CROSS_COMPILE)gcc`' and '`$(CROSS_COMPILE)g++`' respectively in case the user does not set said variables. But by the time this is specified, `make` has already set these variables to the [GNU default values](https://github.com/mupen64plus/mupen64plus-ui-console/pull/61#issuecomment-693795575). Therefore, the syntax '?=' detects existing variables...

Looking for alternatives for my specific case, which is to test the compilation with each and every one of the compilers at my disposal.

There are three solutions:

1. 
```
export CC=gcc-9
export CXX=g++-9
make -e all
```

2. 
```
export CC=gcc-6
export CXX=g++-6
make CC=$CC CXX=$CXX all
```

3. 
```
export CC=clang-5.0
export CXX=clang++-5.0
mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/cc
rm -f $HOME/.local/bin/gcc
rm -f $HOME/.local/bin/c++
rm -f $HOME/.local/bin/g++
ln -s -T /usr/bin/$CC $HOME/.local/bin/cc
ln -s -T /usr/bin/$CC $HOME/.local/bin/gcc
ln -s -T /usr/bin/$CXX $HOME/.local/bin/c++
ln -s -T /usr/bin/$CXX $HOME/.local/bin/g++
make all
```

That's it, I think you can close #62

**Pull request merged**
