### PR TITLE
Small optimizations for CI/CD and make artifacts easier to handle...

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**

### CODE REVIEW

**Comment by Narann** [comment]
Maybe I'm out of the loop (if so, give me the link to the discussion), but what problem are you trying to solve with those modifications. Looks less clean to me than the original.

**Comment by Jj0YzL5nvJ** [comment]
Certainly this new code is more redundant and looks worse to preserve familiarity with its counterparts from the other repositories.
I will put some examples of how branches and artifacts are currently accessed.

Example 1:
URL to [mupen64plus-core/branch/master](https://ci.appveyor.com/project/Narann/mupen64plus-core/branch/master).
URL to [mupen64plus-core/build/artifacts?branch=master](https://ci.appveyor.com/project/Narann/mupen64plus-core/build/artifacts?branch=master).

URL to [gliden64/branch/master](https://ci.appveyor.com/project/gonetz/gliden64/branch/master)
URL to [gliden64/build/artifacts?branch=master](https://ci.appveyor.com/project/gonetz/gliden64/build/artifacts?branch=master)

Example 2 (job profile...):
URL for DD [mupen64plus-core_v2.5.9-156-gfb50105a_x86-Release.7z](https://ci.appveyor.com/api/projects/Narann/mupen64plus-core/artifacts/build/mupen64plus-core_v2.5.9-156-gfb50105a_x86-Release.7z?branch=master&pr=false&job=Configuration:%20Release;%20Platform:%20Win32)
URL for DD [mupen64plus-core_v2.5.9-156-gfb50105a_x64-NewDynarec.7z](https://ci.appveyor.com/api/projects/Narann/mupen64plus-core/artifacts/build/mupen64plus-core_v2.5.9-156-gfb50105a_x64-NewDynarec.7z?branch=master&pr=false&job=Configuration:%20New_Dynarec_Release;%20Platform:%20x64)

URL for DD [GLideN64-37a3d6e7-for_Mupen64Plus.7z](https://ci.appveyor.com/api/projects/gonetz/gliden64/artifacts/build/GLideN64-37a3d6e7-for_Mupen64Plus.7z?branch=master&pr=false)
URL for DD [GLideN64-37a3d6e7-for_Mupen64Plus_x64.7z](https://ci.appveyor.com/api/projects/gonetz/gliden64/artifacts/build/GLideN64-37a3d6e7-for_Mupen64Plus_x64.7z?branch=master&pr=false)

Example 3 (buildjobs ID consistency):
URL for alter DD [mupen64plus-core_v2.5.9-156-gfb50105a_x86-Release.7z](https://ci.appveyor.com/api/buildjobs/6v4ujugiptqt5on5/artifacts/build%2Fmupen64plus-core_v2.5.9-156-gfb50105a_x86-Release.7z)
URL for alter DD [mupen64plus-core_v2.5.9-156-gfb50105a_x64-NewDynarec.7z](https://ci.appveyor.com/api/buildjobs/7cm5eopl6rgtt5tp/artifacts/build%2Fmupen64plus-core_v2.5.9-156-gfb50105a_x64-NewDynarec.7z)

URL for alter DD [GLideN64-37a3d6e7-for_Mupen64Plus.7z](https://ci.appveyor.com/api/buildjobs/27jtysggvquy6kl1/artifacts/build%2FGLideN64-37a3d6e7-for_Mupen64Plus.7z)
URL for alter DD [GLideN64-37a3d6e7-for_Mupen64Plus_x64.7z](https://ci.appveyor.com/api/buildjobs/27jtysggvquy6kl1/artifacts/build%2FGLideN64-37a3d6e7-for_Mupen64Plus_x64.7z)

Example 4: (more uglier scripts, see `filepkg` and `buildid`):
<details>
  <summary>mupen64plus x86:</summary>

```
#!/bin/bash
set -e

PACKAGES=WIP/Mupen64Plus_x64
mkdir -p $PACKAGES
cd $PACKAGES

M64P_COMPONENTS="0 1 2 3 4 5 6 7 8"
for NUM in ${M64P_COMPONENTS}; do
    if [ "${NUM}" = "0" ]; then
        filepkg=mupen64plus-core_v2.5.9-107-g7b73d2db_x64-Release.7z
        buildid=orp9up69rl23vore
    elif  [ "${NUM}" = "1" ]; then
        filepkg=mupen64plus-ui-console_v2.5.9-15-g96834d5_x64.7z
        buildid=932359ulueqy6el6
    elif  [ "${NUM}" = "2" ]; then
        filepkg=mupen64plus-audio-sdl_v2.5.9-14-g1acd163_x64.7z
        buildid=cxe6g5vsb961omgl
    elif  [ "${NUM}" = "3" ]; then
        filepkg=mupen64plus-input-sdl_v2.5.9-22-g0d7820e_x64.7z
        buildid=uateml2x470pa57w
    elif  [ "${NUM}" = "4" ]; then
        filepkg=mupen64plus-rsp-cxd4_v2.5.9-28-g094c664_x64.7z
        buildid=md8bt06jv463b08k
    elif  [ "${NUM}" = "5" ]; then
        filepkg=mupen64plus-rsp-hle_v2.5.9-17-gbb56985_x64.7z
        buildid=8x8efgo15eseelsv
    elif  [ "${NUM}" = "6" ]; then
        filepkg=mupen64plus-video-glide64mk2_v2.5.9-17-gaecf15e_x64.7z
        buildid=nt8akqybim4t320a
    elif  [ "${NUM}" = "7" ]; then
        filepkg=mupen64plus-video-rice_v2.5.9-20-g7ce0bf0_x64.7z
        buildid=ppqa4e677b2n0tkw
    else
        filepkg=GLideN64-7a38e804-for_Mupen64Plus_x64.7z
        buildid=gnvfeu45wn1wdk68
    fi
    curl -L -o ${filepkg} https://ci.appveyor.com/api/buildjobs/${buildid}/artifacts/build/${filepkg}
    7z x -y ${filepkg} -o../../Mupen64Plus_x64
done

filepkg=angrylion-plus_r8-38-4039a55_x86_64_20201004.7z
curl -L -o $filepkg https://i.fiery.me/KM01O.7z
7z x -y $filepkg -o../btmp
cp -f ../btmp/Mupen64Plus_x64/m*.dll ../../Mupen64Plus_x64

filepkg=m64p-win64-3116080.zip
curl -L -o $filepkg https://github.com/loganmc10/m64p/releases/download/Nov302020/$filepkg
7z x -y $filepkg -o../btmp
cp -f ../btmp/mupen64plus/libgcc_s_seh*.dll ../../Mupen64Plus_x64
cp -f ../btmp/mupen64plus/libstdc++*.dll ../../Mupen64Plus_x64
cp -f ../btmp/mupen64plus/libwinpthread*.dll ../../Mupen64Plus_x64
cp -f ../btmp/mupen64plus/mupen64plus-rsp-parallel.dll ../../Mupen64Plus_x64

rm -rf ../btmp
```

</details>

<details>
  <summary>mupen64plus x64:</summary>

```
#!/bin/bash
set -e

PACKAGES=WIP/Mupen64Plus_x86
mkdir -p $PACKAGES
cd $PACKAGES

M64P_COMPONENTS="0 1 2 3 4 5 6 7 8"
for NUM in ${M64P_COMPONENTS}; do
    if [ "${NUM}" = "0" ]; then
        filepkg=mupen64plus-core_v2.5.9-107-g7b73d2db_x86-Release.7z
        buildid=kksjfjk5d9rkefoc
    elif  [ "${NUM}" = "1" ]; then
        filepkg=mupen64plus-ui-console_v2.5.9-15-g96834d5_x86.7z
        buildid=gybqvxeq0a2jjd8x
    elif  [ "${NUM}" = "2" ]; then
        filepkg=mupen64plus-audio-sdl_v2.5.9-14-g1acd163_x86.7z
        buildid=t8s697d0nqm3ocod
    elif  [ "${NUM}" = "3" ]; then
        filepkg=mupen64plus-input-sdl_v2.5.9-22-g0d7820e_x86.7z
        buildid=g389m2ip7eua7ifl
    elif  [ "${NUM}" = "4" ]; then
        filepkg=mupen64plus-rsp-cxd4_v2.5.9-28-g094c664_x86.7z
        buildid=205f2dib8iap735m
    elif  [ "${NUM}" = "5" ]; then
        filepkg=mupen64plus-rsp-hle_v2.5.9-17-gbb56985_x86.7z
        buildid=mx6ntwce0gak5okl
    elif  [ "${NUM}" = "6" ]; then
        filepkg=mupen64plus-video-glide64mk2_v2.5.9-17-gaecf15e_x86.7z
        buildid=784hr5al5hktln5m
    elif  [ "${NUM}" = "7" ]; then
        filepkg=mupen64plus-video-rice_v2.5.9-20-g7ce0bf0_x86.7z
        buildid=h2q0mukud68lh1m0
    else
        filepkg=GLideN64-7a38e804-for_Mupen64Plus.7z
        buildid=gnvfeu45wn1wdk68
    fi
    curl -L -o ${filepkg} https://ci.appveyor.com/api/buildjobs/${buildid}/artifacts/build/${filepkg}
    7z x -y ${filepkg} -o../../Mupen64Plus_x86
done

filepkg=angrylion-plus_r8-38-4039a55_x86_64_20201004.7z
curl -L -o $filepkg https://i.fiery.me/KM01O.7z
7z x -y $filepkg -o../btmp
cp -f ../btmp/Mupen64Plus_x86/m*.dll ../../Mupen64Plus_x86

rm -rf ../btmp
```

</details>

**Comment by Jj0YzL5nvJ** [comment]
Even without scripts, new artifacts are easier to point out:
https://ci.appveyor.com/project/Narann/mupen64plus-core/builds/36816171/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-ui-console/builds/36842626/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-audio-sdl/builds/36816163/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-input-sdl/builds/36842622/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-rsp-cxd4/builds/36816146/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-rsp-hle/builds/36816086/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-video-glide64mk2/builds/36842619/artifacts
https://ci.appveyor.com/project/Narann/mupen64plus-video-rice/builds/36842614/artifacts

Isn't that an improvement?

**Comment by Narann** [comment]
My concerns are about the job removal in favor of a single, longer job, this in order to get artifacts more easily.

Why not using this:

``` bash
API_URL="https://ci.appveyor.com/api"
USER="loganmc10"
PROJ_NAME="mupen64plus-core"
URI="$API_URL/projects/$USER/$PROJ_NAME"
$PROJECT=$(curl -sS --header "Content-type: application/json" "$URI")
JOB_ID=$(echo $PROJECT | jq -r '.build.jobs[0].jobId')

URI="$API_URL/buildjobs/$JOB_ID/artifacts"
ARTIFACTS=$(curl -sS --header "Content-type: application/json" "$URI")
FILE_NAME=$(echo $ARTIFACTS | jq -r '.[0].fileName')
echo $FILE_NAME

wget https://ci.appveyor.com/api/buildjobs/$JOB_ID/artifacts/$FILE_NAME
```

Source: https://devops.datenkollektiv.de/how-to-download-an-artifact-from-appveyor-without-powershell.html

Replace `jobs[0]` by `jobs[1]` for second job and `[0].fileName` by `[1].fileName`, `[2].fileName`, etc for other file names.

It works on my side.

I think we should use the AppVeyor API instead of modifying the way the jobs are managed.

**Comment by Narann** [comment]
You can get array length using:

```bash
$ echo $PROJECT | jq -r '.build.jobs | length'
4
```

**Comment by Narann** [comment]
I did a script:

``` bash
#!/bin/bash
API_URL="https://ci.appveyor.com/api"
USER="loganmc10"

M64P_PROJS="mupen64plus-core mupen64plus-ui-console"
for PROJ_NAME in ${M64P_PROJS}; do
  echo "Project" $PROJ_NAME
  URI="$API_URL/projects/$USER/$PROJ_NAME"
  PROJECT=$(curl -sS --header "Content-type: application/json" "$URI")
  JOB_COUNT=$(echo $PROJECT | jq -r '.build.jobs | length')
  
  if [[ "$JOB_COUNT" == '0' ]]; then
    continue
  fi
  
  echo $JOB_COUNT "jobs"
  for i in $(seq 0 $(($JOB_COUNT-1))); do 

    JOB_ID=$(echo $PROJECT | jq -r '.build.jobs['$i'].jobId')
    echo " Job id" $JOB_ID
    URI="$API_URL/buildjobs/$JOB_ID/artifacts"
    ARTIFACTS=$(curl -sS --header "Content-type: application/json" "$URI")
    ARTIFACT_COUNT=$(echo $ARTIFACTS | jq -r 'length')
    echo " " $ARTIFACT_COUNT "artifacts"
    
    if [[ "$ARTIFACT_COUNT" == '0' ]]; then
      continue
    fi
    
    for j in $(seq 0 $(($ARTIFACT_COUNT-1))); do
      FILE_NAME=$(echo $ARTIFACTS | jq -r '.['$j'].fileName')
      FILE_URL=https://ci.appveyor.com/api/buildjobs/$JOB_ID/artifacts/$FILE_NAME
      echo $FILE_URL
      #wget $FILE_URL
    done
  done
done
```

Put this in a file and make it executable (for conditions to work) and execute it.

Dont forget to change the `USER` variable to someone generating artifacts properly.

I just tested and it works for me.

**Comment by Jj0YzL5nvJ** [comment]
The API is really limited, I want something more like:
```
URI="$API_URL/projects/$USER/$PROJ_NAME/branch/master"
```

But for the latest successfully compiled artifacts... but thanks to your code, I figured "a better way" (hack) to query github directly without needing to query appveyor. Thanks for that, now I just need inspiration as it's tedious... I need to implement functions.

> My concerns are about the job removal in favor of a single, longer job, this in order to get artifacts more easily.

I don't like it but I agree with one thing, giving users more options (artifacts) only ends up confusing them...

**Pull request closed without merging**
